/*Proceso para aumento de amigos */
/* Revisión y aplicación de aumento de amigos */

CREATE OR ALTER PROCEDURE AumentoAmigos  as
begin
	UPDATE USUARIO 
		SET CANT_MAX_AMIGOS = CANT_MAX_AMIGOS +  ( 
			SELECT  COUNT(1)
			FROM  PUBLICACION P 
			WHERE  (P.ID_USUARIO = USUARIO.ID_USUARIO  AND ((SELECT COUNT(1)
					FROM BITACORA
					WHERE ID_PUBLICACION = P.ID_PUBLICACION AND ID_TIPO_ACCION = 1 )
				-(SELECT COUNT(1)
					FROM BITACORA
					WHERE ID_PUBLICACION = P.ID_PUBLICACION AND ID_TIPO_ACCION = 2) 
				- (SELECT COUNT(1)
					FROM BITACORA
					WHERE ID_PUBLICACION = P.ID_PUBLICACION AND ID_TIPO_ACCION = 3)
				+(SELECT COUNT(1)
					FROM BITACORA
					WHERE ID_PUBLICACION = P.ID_PUBLICACION AND ID_TIPO_ACCION = 4)
				> 14))) ;
end

